"""empty message

Revision ID: 3113641c3a44
Revises: 
Create Date: 2019-02-09 14:23:01.307782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3113641c3a44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accepteds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('affiliations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('node_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('code', sa.String(length=60), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('temp_aspects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('temp_imps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('yes_no',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('experts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=60), nullable=True),
    sa.Column('last_name', sa.String(length=60), nullable=True),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('email', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('title_id', sa.Integer(), nullable=True),
    sa.Column('affiliation_id', sa.Integer(), nullable=True),
    sa.Column('discipline', sa.String(length=60), nullable=True),
    sa.Column('uni_work', sa.String(length=60), nullable=True),
    sa.Column('country', sa.String(length=60), nullable=True),
    sa.Column('accepted_id', sa.Integer(), nullable=True),
    sa.Column('specialization', sa.String(length=200), nullable=True),
    sa.Column('personal_descr', sa.String(length=1000), nullable=True),
    sa.Column('permission_mention', sa.String(length=15), nullable=True),
    sa.Column('permission_add_question', sa.String(length=15), nullable=True),
    sa.Column('core_exp', sa.String(length=3), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['accepted_id'], ['accepteds.id'], ),
    sa.ForeignKeyConstraint(['affiliation_id'], ['affiliations.id'], ),
    sa.ForeignKeyConstraint(['title_id'], ['titles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_experts_core_exp'), 'experts', ['core_exp'], unique=False)
    op.create_index(op.f('ix_experts_country'), 'experts', ['country'], unique=False)
    op.create_index(op.f('ix_experts_discipline'), 'experts', ['discipline'], unique=False)
    op.create_index(op.f('ix_experts_email'), 'experts', ['email'], unique=True)
    op.create_index(op.f('ix_experts_first_name'), 'experts', ['first_name'], unique=False)
    op.create_index(op.f('ix_experts_last_name'), 'experts', ['last_name'], unique=False)
    op.create_index(op.f('ix_experts_permission_add_question'), 'experts', ['permission_add_question'], unique=False)
    op.create_index(op.f('ix_experts_permission_mention'), 'experts', ['permission_mention'], unique=False)
    op.create_index(op.f('ix_experts_uni_work'), 'experts', ['uni_work'], unique=False)
    op.create_index(op.f('ix_experts_username'), 'experts', ['username'], unique=True)
    op.create_table('factors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expert_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('factor_A', sa.String(length=60), nullable=True),
    sa.Column('factor_B', sa.String(length=60), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('temp_aspect_id', sa.Integer(), nullable=True),
    sa.Column('temp_imp_id', sa.Integer(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('factor_C', sa.String(length=60), nullable=True),
    sa.Column('factor_D', sa.String(length=60), nullable=True),
    sa.Column('notes_A', sa.String(length=500), nullable=True),
    sa.Column('notes_B', sa.String(length=500), nullable=True),
    sa.Column('notes_C', sa.String(length=500), nullable=True),
    sa.Column('notes_D', sa.String(length=500), nullable=True),
    sa.Column('notes_relation', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['expert_id'], ['experts.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.ForeignKeyConstraint(['temp_aspect_id'], ['temp_aspects.id'], ),
    sa.ForeignKeyConstraint(['temp_imp_id'], ['temp_imps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expert_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('factor', sa.String(length=60), nullable=True),
    sa.Column('threshold', sa.Integer(), nullable=True),
    sa.Column('temp_aspect_id', sa.Integer(), nullable=True),
    sa.Column('temp_imp_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('node_type_id', sa.Integer(), nullable=True),
    sa.Column('notes_factor', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['expert_id'], ['experts.id'], ),
    sa.ForeignKeyConstraint(['node_type_id'], ['node_types.id'], ),
    sa.ForeignKeyConstraint(['temp_aspect_id'], ['temp_aspects.id'], ),
    sa.ForeignKeyConstraint(['temp_imp_id'], ['temp_imps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('treatment_factors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expert_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('treat_factor', sa.String(length=60), nullable=True),
    sa.Column('effect_on_factor', sa.String(length=60), nullable=True),
    sa.Column('treatment_weight', sa.Integer(), nullable=True),
    sa.Column('relation_temp', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('temp_imp_data', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['expert_id'], ['experts.id'], ),
    sa.ForeignKeyConstraint(['relation_temp'], ['temp_aspects.id'], ),
    sa.ForeignKeyConstraint(['temp_imp_data'], ['temp_imps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expert_id', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('factor_A', sa.Integer(), nullable=True),
    sa.Column('factor_B', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('temp_aspect_id', sa.Integer(), nullable=True),
    sa.Column('temp_imp_id', sa.Integer(), nullable=True),
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('notes_relation', sa.String(length=500), nullable=True),
    sa.Column('sup_lit', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['expert_id'], ['experts.id'], ),
    sa.ForeignKeyConstraint(['factor_A'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['factor_B'], ['nodes.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['operators.id'], ),
    sa.ForeignKeyConstraint(['temp_aspect_id'], ['temp_aspects.id'], ),
    sa.ForeignKeyConstraint(['temp_imp_id'], ['temp_imps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('literature_factors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factor_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['factor_id'], ['factors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('literature_treat_factors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factor_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['factor_id'], ['treatment_factors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('literature_treat_factors')
    op.drop_table('literature_factors')
    op.drop_table('edges')
    op.drop_table('treatment_factors')
    op.drop_table('nodes')
    op.drop_table('factors')
    op.drop_index(op.f('ix_experts_username'), table_name='experts')
    op.drop_index(op.f('ix_experts_uni_work'), table_name='experts')
    op.drop_index(op.f('ix_experts_permission_mention'), table_name='experts')
    op.drop_index(op.f('ix_experts_permission_add_question'), table_name='experts')
    op.drop_index(op.f('ix_experts_last_name'), table_name='experts')
    op.drop_index(op.f('ix_experts_first_name'), table_name='experts')
    op.drop_index(op.f('ix_experts_email'), table_name='experts')
    op.drop_index(op.f('ix_experts_discipline'), table_name='experts')
    op.drop_index(op.f('ix_experts_country'), table_name='experts')
    op.drop_index(op.f('ix_experts_core_exp'), table_name='experts')
    op.drop_table('experts')
    op.drop_table('yes_no')
    op.drop_table('titles')
    op.drop_table('temp_imps')
    op.drop_table('temp_aspects')
    op.drop_table('operators')
    op.drop_table('node_types')
    op.drop_table('affiliations')
    op.drop_table('accepteds')
    # ### end Alembic commands ###
